stages:
  pull_data:
    cmd: python scripts/pull_data.py
    deps:
      - params.yaml
    outs:
      - data/20k_partition

  data_prep:
    cmd: python scripts/data_prep.py
    deps:
      - data/20k_partition
      - params.yaml
    outs:
      - data/train
      - data/val
      - data/test

  model_train_eval:
    cmd: python scripts/model_train_eval.py
    deps:
      - data/train
      - data/val
      - data/test
      - partition
      - params.yaml
    outs:
      - models
      - reports
      - figures
